# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AKThread',
            fields=[
                ('uid', models.CharField(max_length=249, primary_key=True, serialize=False)),
                ('title', models.CharField(default='new post', max_length=257)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.JawnUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AKThreadCategory',
            fields=[
                ('uid', models.CharField(max_length=249, primary_key=True, serialize=False)),
                ('title', models.CharField(default='new category', max_length=248)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='akthread',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akcat', to='krogoth_social.AKThreadCategory'),
        ),
        migrations.AddField(
            model_name='akthread',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broodling', to='krogoth_social.AKThread'),
        ),
        migrations.AddField(
            model_name='akthread',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_krogoth_social.akthread_set+', to='contenttypes.ContentType'),
        ),
    ]
