# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AKThread',
            fields=[
                ('uid', models.CharField(max_length=249, primary_key=True, serialize=False)),
                ('title', models.CharField(default='new post', max_length=257)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AKThreadCategory',
            fields=[
                ('uid', models.CharField(max_length=249, primary_key=True, serialize=False)),
                ('title', models.CharField(default='new category', max_length=248)),
                ('description', models.CharField(default='No description.', max_length=248)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForumThreadCategory',
            fields=[
                ('uid', models.CharField(max_length=249, primary_key=True, serialize=False)),
                ('title', models.CharField(default='new category', max_length=248)),
                ('description', models.CharField(default='No description.', max_length=248)),
                ('total_threads', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('img_url', models.CharField(blank=True, max_length=249, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumThreadOP',
            fields=[
                ('uid', models.CharField(max_length=249, primary_key=True, serialize=False)),
                ('title', models.CharField(default='new post', max_length=257)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('not_deleted', models.BooleanField(default=True)),
                ('content', models.TextField(default='')),
                ('total_likes', models.IntegerField(default=0)),
                ('total_replies', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.JawnUser')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krogoth_social.ForumThreadCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ForumThreadReply',
            fields=[
                ('uid', models.CharField(max_length=249, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('not_deleted', models.BooleanField(default=True)),
                ('content', models.TextField(default='')),
                ('total_likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.JawnUser')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krogoth_social.ForumThreadOP')),
            ],
        ),
        migrations.CreateModel(
            name='AKThreadSocialMedia',
            fields=[
                ('akthread_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='krogoth_social.AKThread')),
                ('type', models.CharField(choices=[('text', 'text'), ('article', 'article'), ('video', 'video'), ('image', 'image')], default='text', max_length=40)),
                ('text_body', models.TextField()),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('krogoth_social.akthread',),
        ),
        migrations.AddField(
            model_name='akthread',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.JawnUser'),
        ),
        migrations.AddField(
            model_name='akthread',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ak_threads', to='krogoth_social.AKThreadCategory'),
        ),
        migrations.AddField(
            model_name='akthread',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broodling', to='krogoth_social.AKThread'),
        ),
        migrations.AddField(
            model_name='akthread',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_krogoth_social.akthread_set+', to='contenttypes.ContentType'),
        ),
    ]
