# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOOT_SCREEN_HTML', 'Boot Screen Html'), ('NAVBAR_TITLE', 'Nav Bar Title'), ('NAVBAR_LOGO', 'Nav Bar Logo Html'), ('COLOR_THEME', 'Color Palette'), ('LAYOUT_STYLE', 'Layout Style'), ('LAYOUT_MODE', 'Layout Mode')], max_length=255)),
                ('value', models.TextField()),
            ],
        ),
    ]
