# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralWebsiteInfo', '0002_auto_20170711_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbar',
            name='title',
            field=models.CharField(default='Djangular', max_length=55),
        ),
    ]
