# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AngularFuseApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='please use "_" instead of spaces!', max_length=255)),
                ('category', models.CharField(default='Resources', max_length=30)),
                ('js_module', models.TextField(default="(function () \n{ \n\t'use strict'; \n\n\tangular.module('app.FUSE_APP_NAME', ['flow']).config(config); \n\n\n\tfunction config($stateProvider, $translatePartialLoaderProvider, msApiProvider, msNavigationServiceProvider) { \n\t$stateProvider.state('app.FUSE_APP_NAME', { \n\t\turl: '/FUSE_APP_NAME', \n\t\tviews: { \n\t\t\t'content@app': { \n\t\t\t\ttemplateUrl: '/dynamic_lazarus_page/DynamicHTMLInjector/?name=FUSE_APP_NAME', \n\t\t\t\tcontroller: 'FUSE_APP_NAMEController as vm'\n\t\t\t}\n\t\t}, \n\t\tbodyClass: 'file-manager' \n\t}); \n\n\tmsNavigationServiceProvider.saveItem('NAV_HEADER.FUSE_APP_NAME', { \n\t\ttitle: 'FUSE_APP_TITLE', \n\t\ticon: 'FUSE_APP_ICON', \n\t\tstate: 'app.FUSE_APP_NAME', \n\t\tweight: 3 \n\t}); \n   \n\t} \n})();")),
                ('js_controller', models.TextField(default="(function () \n{ \n\t'use strict'; \n\n\tangular.module('app.FUSE_APP_NAME').controller('FUSE_APP_NAMEController', FUSE_APP_NAMEController); \n\n\n\tfunction FUSE_APP_NAMEController() \n\t{ \n\t\t\tvar vm = this; \n\n\t\t\tvm.helloText = 'Welcome to FUSE_APP_NAME'; \n  \n\t} \n})();")),
                ('html_main', models.TextField(default='<h1>Djangular Lazarus</h1>')),
                ('icon', models.CharField(choices=[('icon-cloud', 'icon-cloud'), ('icon-cube', 'icon-cube'), ('icon-cube-outline', 'icon-cube-outline'), ('icon-cog', 'icon-cog'), ('icon-hexagon-outline', 'icon-hexagon-outline'), ('icon-hexagon', 'icon-hexagon'), ('icon-home', 'icon-home'), ('icon-harddisk', 'icon-harddisk'), ('icon-view-list', 'icon-view-list'), ('icon-terrain', 'Terrain'), ('icon-dice', 'Terrain'), ('icon-help', 'Question Mark'), ('icon-layers', 'Layers Cube'), ('icon-memory', 'Memory Chip'), ('icon-package-variant-closed', 'Package Cube Closed'), ('icon-package-variant', 'Package Opened'), ('icon-view-agenda', 'Data Agenda'), ('icon-view-array', 'Data Array'), ('icon-view-carousel', 'Data Carousel'), ('icon-view-column', 'Data Column'), ('icon-view-dashboard', 'Data Dashboard'), ('icon-view-day', 'Data Day'), ('icon-view-headline', 'Data Headline'), ('icon-view-list', 'Data List'), ('icon-view-module', 'Data Module'), ('icon-view-quilt', 'Data Quilt'), ('icon-view-stream', 'Data Stream'), ('icon-view-week', 'Data Week'), ('icon-web', 'Web Globe Atlas'), ('icon-ubuntu', 'icon-ubuntu'), ('icon-linux', 'icon-linux'), ('icon-apple', 'icon-apple'), ('icon-windows', 'icon-windows')], default='icon-hexagon-outline', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FuseAppComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('parent_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_lazarus_page.AngularFuseApplication')),
            ],
        ),
        migrations.CreateModel(
            name='NgIncludedHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contents', models.TextField(default='<h4> Djangular Error: There is nothing here yet! </h4>')),
                ('url_helper', models.CharField(default='/dynamic_lazarus_page/NgIncludedHtml/?name=_NAME_', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('remote_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('http_usr', models.CharField(blank=True, max_length=255, null=True)),
                ('http_accept', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
