# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AngularFuseApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(upload_to='cars')),
            ],
        ),
        migrations.CreateModel(
            name='FuseAppComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('parent_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_lazarus_page.AngularFuseApplication')),
            ],
        ),
        migrations.CreateModel(
            name='FuseApplicationComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('parent_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_lazarus_page.AngularFuseApplication')),
            ],
        ),
        migrations.CreateModel(
            name='SuperBasicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_string', models.CharField(max_length=100)),
                ('basic_bool', models.BooleanField(default=False)),
                ('basic_int', models.IntegerField()),
            ],
        ),
    ]
