# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-03 17:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JawnUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('about_me', models.CharField(blank=True, max_length=400, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('faction', models.CharField(blank=True, choices=[('core', 'Core'), ('arm', 'Arm')], max_length=10, null=True)),
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jawn_user', to=settings.AUTH_USER_MODEL)),
                ('follows', models.ManyToManyField(blank=True, null=True, related_name='followers', to='chat.JawnUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateMessageRelationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=150)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='chat.Channel')),
                ('user_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipient', to=settings.AUTH_USER_MODEL)),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('coordinates_long', models.FloatField()),
                ('coordinates_lat', models.FloatField()),
                ('flickr_image', models.CharField(max_length=150, null=True)),
                ('flickr_image_large', models.CharField(max_length=150, null=True)),
                ('google_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.Message')),
                ('type', models.CharField(choices=[('image', 'image')], default='image', max_length=50)),
                ('image_url', models.ImageField(upload_to='media/')),
                ('caption', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('chat.message',),
        ),
        migrations.CreateModel(
            name='LinkMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.Message')),
                ('type', models.CharField(choices=[('link', 'link')], default='link', max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('headline', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('chat.message',),
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.Message')),
                ('type', models.CharField(choices=[('text', 'text')], default='text', max_length=50)),
                ('text', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=('chat.message',),
        ),
        migrations.CreateModel(
            name='YouTubeMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.Message')),
                ('type', models.CharField(choices=[('youtube', 'youtube')], default='youtube', max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('youtube_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('chat.message',),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Channel'),
        ),
        migrations.AddField(
            model_name='message',
            name='jawn_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='chat.JawnUser'),
        ),
        migrations.AddField(
            model_name='message',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_chat.message_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='channel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='chat.JawnUser'),
        ),
    ]
