# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20160214_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemessage',
            name='image_url',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='type',
            field=models.CharField(choices=[('image', 'image')], default='image', max_length=50),
        ),
        migrations.AlterField(
            model_name='jawnuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='jawnuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='type',
            field=models.CharField(choices=[('text', 'text')], default='text', max_length=50),
        ),
    ]
