# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20160215_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.Message')),
                ('type', models.CharField(choices=[('text', 'text')], default='link', max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('iamge_url', models.URLField(blank=True, null=True)),
                ('headline', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('chat.message',),
        ),
    ]
