# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20160215_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessageRelationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=150)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='chat.Channel')),
                ('user_recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipient', to=settings.AUTH_USER_MODEL)),
                ('user_sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('coordinates_long', models.DecimalField(decimal_places=8, max_digits=8)),
                ('coordinates_lat', models.DecimalField(decimal_places=8, max_digits=8)),
                ('flickr_image', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
