# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_privatemessagerelationships_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessagerelationships',
            name='user_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatemessagerelationships',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
