# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20160227_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
