# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20160228_2013'),
        ('chat', '0005_auto_20160514_0322'),
    ]

    operations = [
    ]
