# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 05:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20160518_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='google_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
