# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-05 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_region_google_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.Message')),
                ('type', models.CharField(choices=[('youtube', 'youtube')], default='youtube', max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('youtube_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('chat.message',),
        ),
        migrations.AddField(
            model_name='region',
            name='flickr_image_large',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='linkmessage',
            name='type',
            field=models.CharField(choices=[('link', 'link')], default='link', max_length=50),
        ),
    ]
