# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseSandbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuploadtrackersb',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlogsb',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
