# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseSandbox', '0002_auto_20170707_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAnnihilationUploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('download_url', models.CharField(max_length=255)),
                ('system_path', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(max_length=10)),
                ('HPI_Extractor_Log', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
