# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseSandbox', '0003_totalannihilationuploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalannihilationuploadedfile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='totalannihilationuploadedfile',
            name='is_terminated',
            field=models.BooleanField(default=True),
        ),
    ]
