# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangular', '0003_auto_20170717_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangulardirective',
            name='directive_js',
            field=models.TextField(default="(function ()\n{\n\t'use strict';\n\tangular\n\t\t.module('app.FUSE_APP_NAME')\n\t\t.directive('_DJANGULAR_DIRECTIVE_NAME_', _DJANGULAR_DIRECTIVE_NAME_Directive);\n\t/** @ngInject */\n\tfunction _DJANGULAR_DIRECTIVE_NAME_Directive()\n\t{\n\t\treturn {restrict: 'AE',replace: 'true',template: '_DJANGULAR_DIRECTIVE_TITLE_'};\n\n\t}})\n();"),
        ),
        migrations.AlterField(
            model_name='djangularmasterviewcontroller',
            name='module_js',
            field=models.TextField(default="(function () \n{ \n\t'use strict'; \n\tangular.module('app.FUSE_APP_NAME', ['flow']).config(config); \n\n\tfunction config($stateProvider, $translatePartialLoaderProvider, msApiProvider, msNavigationServiceProvider) { \n\t$stateProvider\n\t.state('app.FUSE_APP_NAME', { \n\t\turl: '/FUSE_APP_NAME', \n\t\tviews: { \n\t\t\t'content@app': { \n\t\t\t\ttemplateUrl: '/Djangular/DynamicHTMLInjector/?name=FUSE_APP_NAME', \n\t\t\t\tcontroller: 'FUSE_APP_NAMEController as vm'\n\t\t\t}\n\t\t} \n\t})  \n\t_DJANGULAR_SLAVE_VC_INJECTION_POINT_; /* Djangular Slave VCs automatically injected here. */ \n\tmsNavigationServiceProvider.saveItem('NAV_HEADER.FUSE_APP_NAME', { \n\t\ttitle: 'FUSE_APP_TITLE', \n\t\ticon: 'FUSE_APP_ICON', \n\t\tstate: 'app.FUSE_APP_NAME', \n\t\tweight: 3 \n\t});    \n\t} \n})();"),
        ),
        migrations.AlterField(
            model_name='djangularservice',
            name='service_js',
            field=models.TextField(default="(function ()\n{\n\t'use strict';\n\tangular\n\t\t.module('app.FUSE_APP_NAME')\n\t\t.factory('_DJANGULAR_SERVICE_NAME_', _DJANGULAR_SERVICE_NAME_);\n\t/** @ngInject */\n\tfunction _DJANGULAR_SERVICE_NAME_($log)\n\t{\n\t\t$log.log('Hello. The service _DJANGULAR_SERVICE_NAME_ is online ! ! !');\n\n\t\tvar service = {\n\t\t\ttestThisService: testThisService\n\t\t};\n\nfunction testThisService()\n\t\t{\n\t\t\t$log.log('_DJANGULAR_SERVICE_NAME_ is working properly.');\n\t\t}\n\t\treturn service;\n\t}\n})();"),
        ),
        migrations.AlterField(
            model_name='djangularslaveviewcontroller',
            name='controller_js',
            field=models.TextField(default="(function () \n{ \n\t'use strict'; \n\tangular.module('app.FUSE_APP_NAME').controller('FUSE_APP_NAMEController', FUSE_APP_NAMEController); \n\tfunction FUSE_APP_NAMEController() \n\t{ \n\t\t\tvar vm = this; \n\t\t\t vm.viewName = 'FUSE_APP_NAME'; \n\t} \n})();"),
        ),
        migrations.AlterField(
            model_name='djangularslaveviewcontroller',
            name='view_html',
            field=models.TextField(default='<h1>{{ vm.viewName }}</h1>'),
        ),
    ]
