# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NgIncludedHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contents', models.TextField(default='<h4> krogoth_gantry Error: There is nothing here yet! </h4>')),
                ('url_helper', models.CharField(default='Dont worry about this text.', help_text='krogoth_gantry will take care of this.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NgIncludedJs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contents', models.TextField(default='<h4> krogoth_gantry Error: There is nothing here yet! </h4>')),
                ('url_helper', models.CharField(default='Dont worry about this text.', help_text='krogoth_gantry will take care of this.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('remote_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('http_usr', models.CharField(blank=True, max_length=255, null=True)),
                ('http_accept', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
