# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('krogoth_gantry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgIncludedHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contents', models.TextField(default='<h4> krogoth_gantry Error: There is nothing here yet! </h4>')),
                ('url_helper', models.CharField(default='Dont worry about this text.', help_text='krogoth_gantry will take care of this.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NgIncludedJs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contents', models.TextField(default='<h4> krogoth_gantry Error: There is nothing here yet! </h4>')),
                ('url_helper', models.CharField(default='Dont worry about this text.', help_text='krogoth_gantry will take care of this.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('remote_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('http_usr', models.CharField(blank=True, max_length=255, null=True)),
                ('http_accept', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncludedHtmlMaster',
            fields=[
                ('ngincludedhtml_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moho_extractor.NgIncludedHtml')),
                ('sys_path', models.CharField(default='/usr/src/app/', max_length=256)),
                ('master_vc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_html', to='krogoth_gantry.KrogothGantryMasterViewController')),
            ],
            options={
                'abstract': False,
            },
            bases=('moho_extractor.ngincludedhtml',),
        ),
        migrations.CreateModel(
            name='IncludedJsMaster',
            fields=[
                ('ngincludedjs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moho_extractor.NgIncludedJs')),
                ('master_vc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_js', to='krogoth_gantry.KrogothGantryMasterViewController')),
            ],
            options={
                'abstract': False,
            },
            bases=('moho_extractor.ngincludedjs',),
        ),
        migrations.AddField(
            model_name='ngincludedjs',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_moho_extractor.ngincludedjs_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='ngincludedhtml',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_moho_extractor.ngincludedhtml_set+', to='contenttypes.ContentType'),
        ),
    ]
