# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 15:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCallbackEndpoint',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True)),
                ('full_uri', models.URLField(primary_key=True, serialize=False)),
                ('uri_request_params', django.contrib.postgres.fields.jsonb.JSONField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_krogoth_3rdparty_api.basecallbackendpoint_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
