#!/bin/bash

echo Total Annihilation Game Data Consolidator
sleep 0.2s
echo Developed By CiniCraft Copyright 2017 All Rights Reserved
sleep 0.2s
echo
echo Feel free to edit this bash script!
sleep 0.2s
echo

for f in ~/.wine/drive_c/HPI_tools/UnitsToPack/*; 

do wine ~/.wine/drive_c/HPI_tools/HPIDump.exe -o ~/.wine/drive_c/HPI_tools/UnitsToPack/unpacked $f; 
done


