# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chat', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBNanolatheExamplePlain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(default='Untitled Nanolathe Construct', help_text='The display title for development and documentation.', max_length=140)),
                ('html_code', models.TextField(default='<div>Code has not been generated yet.</div>')),
                ('title', models.CharField(max_length=250)),
                ('num_value', models.IntegerField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kbot_lab.kbnanolatheexampleplain_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'nanolathing blueprints',
                'verbose_name': 'nanolathing blueprint',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KBNanolatheThreadAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(default='Untitled Nanolathe Construct', help_text='The display title for development and documentation.', max_length=140)),
                ('html_code', models.TextField(default='<div>Code has not been generated yet.</div>')),
                ('kb_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kbot_lab.KBNanolatheThreadAbstract')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kbot_lab.kbnanolathethreadabstract_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'nanolathing blueprints',
                'verbose_name': 'nanolathing blueprint',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KBNanolatheUploadAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(default='Untitled Nanolathe Construct', help_text='The display title for development and documentation.', max_length=140)),
                ('html_code', models.TextField(default='<div>Code has not been generated yet.</div>')),
                ('kb_file', models.FileField(upload_to='AbstractUploads')),
            ],
            options={
                'verbose_name': 'nanolathed upload',
                'verbose_name_plural': 'nanolathed uploads',
            },
        ),
        migrations.CreateModel(
            name='KBNanolatheExampleUpload',
            fields=[
                ('kbnanolatheuploadabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbot_lab.KBNanolatheUploadAbstract')),
                ('kbc_uploaded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.JawnUser')),
            ],
            options={
                'verbose_name_plural': 'nanolathing blueprints',
                'verbose_name': 'nanolathing blueprint',
                'abstract': False,
            },
            bases=('kbot_lab.kbnanolatheuploadabstract',),
        ),
        migrations.AddField(
            model_name='kbnanolatheuploadabstract',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kbot_lab.kbnanolatheuploadabstract_set+', to='contenttypes.ContentType'),
        ),
    ]
