# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-05 05:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AKBowerComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=250)),
                ('package_version', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=251)),
            ],
        ),
        migrations.CreateModel(
            name='AKCustomDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=250)),
                ('package_version', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=251)),
            ],
        ),
        migrations.CreateModel(
            name='AKFoundationAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=90, unique=True)),
                ('first_name', models.CharField(help_text='EXAMPLES: index. index. toolbar. theming.', max_length=140)),
                ('last_name', models.CharField(help_text='EXAMPLES: .controller .route .module .service', max_length=140)),
                ('code', models.TextField(default='Not Yet Generated.')),
                ('ext', models.CharField(help_text='EXAMPLES: html css js ', max_length=24)),
                ('path', models.CharField(default='/krogoth_core/AKThemes/Pro/', help_text='the path to the folder which contains this code.', max_length=90)),
                ('theme', models.CharField(default='/usr/src/app/krogoth_core/AKThemes/Pro/', max_length=90)),
                ('is_selected_theme', models.BooleanField(default=False)),
                ('custom_key_values', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_krogoth_core.akfoundationabstract_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AKFoundationAngularCore',
            fields=[
            ],
            options={
                'verbose_name': 'Core Application',
                'indexes': [],
                'verbose_name_plural': 'Core Application',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Core Configuration',
                'indexes': [],
                'verbose_name_plural': 'Core Configuration',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationDirectives',
            fields=[
            ],
            options={
                'verbose_name': 'Core Directive',
                'indexes': [],
                'verbose_name_plural': 'Core Directives',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationFilters',
            fields=[
            ],
            options={
                'verbose_name': 'Core Filter',
                'indexes': [],
                'verbose_name_plural': 'Core Filters',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationIndex',
            fields=[
            ],
            options={
                'verbose_name': 'AngularJS Index Foundation',
                'indexes': [],
                'verbose_name_plural': 'AngularJS Index Foundation',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationMain',
            fields=[
            ],
            options={
                'verbose_name': 'AngularJS Main Foundation',
                'indexes': [],
                'verbose_name_plural': 'AngularJS Main Foundation',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationNavigation',
            fields=[
            ],
            options={
                'verbose_name': 'Layout Navigation',
                'indexes': [],
                'verbose_name_plural': 'Layout Navigation',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationQuickPanel',
            fields=[
            ],
            options={
                'verbose_name': 'Layout Quick Panel',
                'indexes': [],
                'verbose_name_plural': 'Layout Quick Panel',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationRESTful',
            fields=[
            ],
            options={
                'verbose_name': 'AngularJS RESTful Foundation',
                'indexes': [],
                'verbose_name_plural': 'AngularJS RESTful Foundation',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationThemingConfiguration',
            fields=[
            ],
            options={
                'verbose_name': 'Core Theming Option',
                'indexes': [],
                'verbose_name_plural': 'Core Theming Options',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationThemingConstant',
            fields=[
            ],
            options={
                'verbose_name': 'Core Theming Constant',
                'indexes': [],
                'verbose_name_plural': 'Core Theming Constants',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationThemingService',
            fields=[
            ],
            options={
                'verbose_name': 'Core Theming Service',
                'indexes': [],
                'verbose_name_plural': 'Core Theming Services',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationToolbar',
            fields=[
            ],
            options={
                'verbose_name': 'AngularJS Toolbar Foundation',
                'indexes': [],
                'verbose_name_plural': 'AngularJS Toolbar Foundation',
                'proxy': True,
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
    ]
