# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 14:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krogoth_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akfoundationangularcore',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationconfig',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationdirectives',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationfilters',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationindex',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationmain',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationnavigation',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationquickpanel',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationrestful',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationthemingconfiguration',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationthemingconstant',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationthemingservice',
            name='akfoundationabstract_ptr',
        ),
        migrations.RemoveField(
            model_name='akfoundationtoolbar',
            name='akfoundationabstract_ptr',
        ),
        migrations.AddField(
            model_name='akfoundationabstract',
            name='custom_key_values',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='akfoundationabstract',
            name='path',
            field=models.CharField(default='/krogoth_core/AKThemes/Pro/', help_text='the path to the folder which contains this code.', max_length=90),
        ),
        migrations.DeleteModel(
            name='AKFoundationAngularCore',
        ),
        migrations.DeleteModel(
            name='AKFoundationConfig',
        ),
        migrations.DeleteModel(
            name='AKFoundationDirectives',
        ),
        migrations.DeleteModel(
            name='AKFoundationFilters',
        ),
        migrations.DeleteModel(
            name='AKFoundationIndex',
        ),
        migrations.DeleteModel(
            name='AKFoundationMain',
        ),
        migrations.DeleteModel(
            name='AKFoundationNavigation',
        ),
        migrations.DeleteModel(
            name='AKFoundationQuickPanel',
        ),
        migrations.DeleteModel(
            name='AKFoundationRESTful',
        ),
        migrations.DeleteModel(
            name='AKFoundationThemingConfiguration',
        ),
        migrations.DeleteModel(
            name='AKFoundationThemingConstant',
        ),
        migrations.DeleteModel(
            name='AKFoundationThemingService',
        ),
        migrations.DeleteModel(
            name='AKFoundationToolbar',
        ),
        migrations.CreateModel(
            name='AKFoundationAngularCore',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationConfig',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationDirectives',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationFilters',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationIndex',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationMain',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationNavigation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationQuickPanel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationRESTful',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationThemingConfiguration',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationThemingConstant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationThemingService',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
        migrations.CreateModel(
            name='AKFoundationToolbar',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_core.akfoundationabstract',),
        ),
    ]
