# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrogothGantryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(default='Untitled krogoth_gantry Application', help_text='Cosmetic display name for this app in the primary navigation view', max_length=55)),
                ('weight', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KrogothGantryDirective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51, unique=True)),
                ('title', models.CharField(default='Untitled krogoth_gantry Directive', help_text='Cosmetic display name for this directive in the primary navigation view', max_length=55)),
                ('directive_js', models.TextField(default="(function ()\n{\n\t'use strict';\n\tangular\n\t\t.module('app.FUSE_APP_NAME')\n\t\t.directive('_DJANGULAR_DIRECTIVE_NAME_', _DJANGULAR_DIRECTIVE_NAME_Directive);\n\t/** @ngInject */\n\tfunction _DJANGULAR_DIRECTIVE_NAME_Directive()\n\t{\n\t\treturn {restrict: 'AE', replace: 'true', template: '_DJANGULAR_DIRECTIVE_TITLE_'};\n\n\t}})\n();")),
            ],
        ),
        migrations.CreateModel(
            name='KrogothGantryIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=75, unique=True)),
                ('prefix', models.CharField(choices=[('FA', 'Font Awesome'), ('MDI', 'Material Design Icon'), ('ENTYPO', 'Entypo')], default='FA', help_text='The icon type, i.e. font awesome, material design, etc...', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='KrogothGantryMasterViewController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(default='Untitled krogoth_gantry Application', help_text='Cosmetic display name for this app in the primary navigation view', max_length=55)),
                ('module_js', models.TextField(default="(function ()\n{\n\t'use strict';\n\tangular.module('app.FUSE_APP_NAME', ['flow']).config(config);\n\n\tfunction config($stateProvider, $translatePartialLoaderProvider, msApiProvider, msNavigationServiceProvider) {\n\t$stateProvider\n\t.state('app.FUSE_APP_NAME', {\n\t\turl: '/FUSE_APP_NAME',\n\t\tviews: {\n\t\t\t'content@app': {\n\t\t\t\ttemplateUrl: '/krogoth_gantry/DynamicHTMLInjector/?name=FUSE_APP_NAME',\n\t\t\t\tcontroller: 'FUSE_APP_NAMEController as vm'\n\t\t\t}\n\t\t}\n\t})\n\t_DJANGULAR_SLAVE_VC_INJECTION_POINT_; /* krogoth_gantry Slave VCs automatically injected here. */\n\t_DJANGULAR_SLAVE_MSAPI_INJECTION_POINT_\n\tmsNavigationServiceProvider.saveItem('AK_NAVCAT_KROGOTH.AK_SUBCATAGORY_KROGOTH.FUSE_APP_NAME', {\n\t\ttitle: 'FUSE_APP_TITLE',\n\t\ticon: 'FUSE_APP_ICON',\n\t\tstate: 'app.FUSE_APP_NAME',\n\t\tweight: 3\n\t});  _DJANGULAR_SLAVE_NAV_SERVICE_INJECTIONS_\n\t}\n})();")),
                ('controller_js', models.TextField(default="(function () {\n    'use strict';\n    angular.module('app.FUSE_APP_NAME').controller('FUSE_APP_NAMEController', FUSE_APP_NAMEController);\n\n    function FUSE_APP_NAMEController() {\n        var vm = this;\n        vm.$onInit = onInit;\n        vm.viewName = 'FUSE_APP_NAME';\n        vm.viewDidLoad = viewDidLoad;\n\n\n        function onInit() {\n            vm.viewDidLoad();\n        }\n\n        function viewDidLoad() {\n            console.log('FUSE_APP_NAME did finish loading');\n        }\n    }\n})();\n\n\n/*\nsh /Vol\n*/\n\n/*\nsh /Volumes/MBP_Backup/arm-prime/docker/KILL_ALL_.sh\n*/\n\n/*\nsh /Volumes/MBP_Backup/arm-prime/docker/run-docker-installed.sh\n*/")),
                ('view_html', models.TextField(default='<h1>{{ vm.viewName }}</h1>\n\n')),
                ('style_css', models.TextField(default='/**/')),
                ('themestyle_is_enabled', models.BooleanField(default=True)),
                ('themestyle', models.TextField(default="\n\n\n/*GLOBALSTYLE*/\n\n\n\n\n    @media only screen and (max-width: 9000px) {\n        md-content.md-default-theme.md-hue-2, md-content.md-hue-2 {\n            background-size: 4000px 4000px !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-opaque-3k.jpg') !important;\n            background-repeat: no-repeat;\n            background-position: left top;\n            background-attachment: fixed !important;\n        }\n\n        .opaque-global {\n            background-size: 4000px 4000px !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-opaque-3k.jpg') !important;\n            background-repeat: no-repeat;\n            background-position: left top;\n            background-attachment: fixed !important;\n        }\n\n        md-sidenav {\n            background-size: 4000px 4000px !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-repeat: no-repeat;\n            background-position: left top;\n            background-attachment: fixed !important;\n        }\n\n        md-toolbar {\n            background-size: 4000px 4000px !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-repeat: no-repeat;\n            background-position: left top;\n            background-attachment: fixed !important;\n        }\n\n        .glass-global {\n            background-attachment: fixed !important;\n            background-size: 4000px 4000px !important;\n            background-position: left top;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n        }\n\n        .glass-test {\n            background-attachment: fixed !important;\n            background-size: 4000px 4000px !important;\n            background-position: left top;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n        }\n\n        body {\n            background-size: 4000px 4000px !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-opaque-3k.jpg') !important;\n            background-repeat: no-repeat;\n            background-position: left top;\n            background-attachment: fixed !important;\n            color: white;\n        }\n    }\n\n    @media only screen and (max-width: 3000px) {\n        md-content.md-default-theme.md-hue-2, md-content.md-hue-2 {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-opaque-3k.jpg') !important;\n            background-size: 3000px 3000px !important;\n            background-position: left top;\n        }\n\n        .opaque-global {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-opaque-3k.jpg') !important;\n            background-size: 3000px 3000px !important;\n            background-position: left top;\n        }\n\n        md-sidenav {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-size: 3000px 3000px !important;\n            background-position: left top;\n        }\n\n        md-toolbar {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-size: 3000px 3000px;\n            background-position: left top;\n        }\n\n        .glass-global {\n            background-size: 3000px 3000px !important;\n            background-position: left top;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n        }\n\n        body {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-size: 3000px 3000px !important;\n            background-position: left top;\n        }\n\n        .glass-test {\n            background-attachment: fixed !important;\n            background-size: 3000px 3000px !important;\n            background-position: left top;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n        }\n    }\n\n    @media only screen and (max-width: 2001px) {\n\n        md-sidenav {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-size: 2000px 2000px !important;\n            background-position: left top;\n        }\n\n        md-toolbar {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-size: 2000px 2000px !important;\n            background-position: left top;\n        }\n\n        md-content.md-default-theme.md-hue-2, md-content.md-hue-2 {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-opaque-3k.jpg') !important;\n            background-size: 2000px 2000px !important;\n            background-position: left top;\n        }\n\n        .opaque-global {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-opaque-3k.jpg') !important;\n            background-size: 2000px 2000px !important;\n            background-position: left top;\n        }\n\n        .glass-global {\n            background-attachment: fixed !important;\n            background-size: 2000px 2000px !important;\n            background-position: left top;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n        }\n\n        .glass-test {\n            background-attachment: fixed !important;\n            background-size: 2000px 2000px !important;\n            background-position: left top;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n        }\n\n        body {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-size: 2000px 2000px !important;\n            background-position: left top;\n        }\n    }\n\n\n    @media only screen and (max-width: 1024px) {\n\n        md-sidenav {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-size: 1024px 1024px !important;\n            background-position: left top;\n        }\n\n        md-toolbar {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-size: 1024px 1024px !important;\n            background-position: left top;\n        }\n\n        md-content.md-default-theme.md-hue-2, md-content.md-hue-2 {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-opaque-3k.jpg') !important;\n            background-size: 1024px 1024px !important;\n            background-position: left top;\n        }\n\n        .opaque-global {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-opaque-3k.jpg') !important;\n            background-size: 1024px 1024px !important;\n            background-position: left top;\n        }\n\n        .glass-global {\n            background-attachment: fixed !important;\n            background-size: 1024px 1024px !important;\n            background-position: left top;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n        }\n\n        .glass-test {\n            background-attachment: fixed !important;\n            background-size: 1024px 1024px !important;\n            background-position: left top;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n        }\n\n        body {\n            background-attachment: fixed !important;\n            background-image: url('/static/fancy_bgs/EPIC_Planet-3-blur-3k.jpg') !important;\n            background-size: 1024px 1024px !important;\n            background-position: left top;\n        }\n    }\n\n    @font-face {\n        font-family: 'haettenschweilerregular';\n        src: url('/static/fonts/haettenschweiler-webfont.woff2') format('woff2'),\n        url('/static/fonts/haettenschweiler-webfont.woff') format('woff');\n        font-weight: normal;\n        font-style: normal;\n    }\n\n    .icon-ta-arm {\n        display: inline-block;\n        width: 30px;\n        height: 30px;\n        background-image: url('/static/ArmLogoVectorWhite.svg');\n        background-repeat: no-repeat;\n        background-position: center center;\n    }\n\n    .icon-ta-core {\n        display: inline-block;\n        width: 30px;\n        height: 30px;\n        background-image: url('/static/CoreLogoVectorWhite.svg');\n        background-repeat: no-repeat;\n        background-position: center center;\n    }\n\n    @-webkit-keyframes MOVE-BG {\n        0% {\n            -webkit-transform: translateX(0%);\n        }\n        50% {\n            -webkit-transform: translateX(-9%);\n        }\n        100% {\n            -webkit-transform: translateX(0%);\n        }\n    }\n\n    @-webkit-keyframes SCALE-INFINITE {\n        0% {\n            -ms-transform: scale(1.0, 1.0); /* IE 9 */\n            -webkit-transform: scale(1.0, 1.0); /* Safari */\n            transform: scale(1.0, 1.0); /* Standard syntax */\n        }\n        50% {\n            -ms-transform: scale(1.01, 1.01); /* IE 9 */\n            -webkit-transform: scale(1.01, 1.01); /* Safari */\n            transform: scale(1.01, 1.01); /* Standard syntax */\n        }\n        100% {\n            -ms-transform: scale(1.0, 1.0); /* IE 9 */\n            -webkit-transform: scale(1.0, 1.0); /* Safari */\n            transform: scale(1.0, 1.0); /* Standard syntax */\n        }\n    }\n\n    .redb {\n        border-radius: 3px;\n        border-style: solid;\n        border-width: 1px;\n        border-color: #D32F2F;\n    }\n    .blueb {\n        border-radius: 3px !important;\n        border-style: solid !important;\n        border-width: 1px !important;\n        border-color: #2196F3 !important;\n    }\n    .var-display {\n        width:60px;\n        padding:5px;\n        border-radius: 10px;\n    }\n\n\n\n/*EndGlobalStyle*/")),
                ('is_enabled', models.BooleanField(default=True, help_text='When disabled, this javascript code and html code will not be loaded.')),
                ('path_to_static', models.CharField(default='NOT_SET', max_length=125)),
                ('is_lazy', models.BooleanField(default=False, help_text='If lazy, this master view controller will not load until accessed.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krogoth_gantry.KrogothGantryCategory')),
                ('djangular_directive', models.ManyToManyField(blank=True, null=True, related_name='displayer', to='krogoth_gantry.KrogothGantryDirective')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KrogothGantryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, unique=True)),
                ('title', models.CharField(default='Untitled krogoth_gantry Service', help_text='Cosmetic display name for this service in the primary navigation view', max_length=55)),
                ('service_js', models.TextField(default="(function () {\n    'use strict';\n    angular\n        .module('app.FUSE_APP_NAME')\n        .factory('_DJANGULAR_SERVICE_NAME_', _DJANGULAR_SERVICE_NAME_);\n\n    /** @ngInject */\n    function _DJANGULAR_SERVICE_NAME_($log, $http, $q) {\n        $log.log('Hello. The service _DJANGULAR_SERVICE_NAME_ is online ! ! !');\n        var service = {\n            getDjangularMasterViewControllers: getDjangularMasterViewControllers\n        };\n\n        function getDjangularMasterViewControllers() {\n            var deferred = $q.defer();\n            $http({\n                method: 'GET',\n                url: '/krogoth_gantry/MasterViewControllerEditorList/'\n            }).then(function successCallback(response) {\n                /// Success\n                deferred.resolve(response.data);\n            }, function errorCallback(response) {\n                /// Fail\n                deferred.reject(response);\n            });\n            return deferred.promise;\n        }\n\n        return service;\n    }\n})();")),
            ],
        ),
        migrations.CreateModel(
            name='KrogothGantrySlaveViewController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='MUST BE EXACT NAME OF MASTER VIEW CONTROLLER.', max_length=56, unique=True)),
                ('title', models.CharField(default='sideNav', help_text='The name for this slave VC.', max_length=55)),
                ('controller_js', models.TextField(default="(function () {\n    'use strict';\n    angular.module('app.FUSE_APP_NAME').controller('_SLAVE_NAME_Controller', _SLAVE_NAME_Controller);\n\n    function _SLAVE_NAME_Controller($stateParams) {\n        var vm = this;\n        vm.$onInit = onInit;\n        vm.viewName = 'FUSE_APP_NAME';\n        vm.viewDidLoad = viewDidLoad;\n        vm.itemId = '';\n\n        function onInit() {\n            console.log('_SLAVE_NAME_ did finish loading');\n            vm.viewDidLoad();\n        }\n\n        function viewDidLoad() {\n            // vm.itemId = $stateParams.theUniqueStateId;\n        }\n    }\n})();\n\n\n/// APPEND THIS TO THE MASTER STATE PROVIDER:\n/*\n*             .state('app.FUSE_APP_NAME.slave', {\n*                url: '/FUSE_APP_NAME/:theUniqueStateId',\n*                views: {\n*                    'main@': {\n*                        templateUrl: '/moho_extractor/NgIncludedHtml/?name=content-only.html',\n*                        controller: 'MainController as vm'\n*                    },\n*                    'content@app.FUSE_APP_NAME.slave': {\n*                        templateUrl: '/krogoth_gantry/DynamicHTMLSlaveInjector/?name=FUSE_APP_SLAVE_NAME',\n*                        controller: 'FUSE_APP_SLAVE_NAMEController as vm'\n*                    }\n*\n*                }\n*            })\n*\n* */")),
                ('view_html', models.TextField(default='<h1>{{ vm.viewName }}</h1>\n\n')),
            ],
        ),
        migrations.AddField(
            model_name='krogothgantrymasterviewcontroller',
            name='djangular_service',
            field=models.ManyToManyField(blank=True, null=True, related_name='provider', to='krogoth_gantry.KrogothGantryService'),
        ),
        migrations.AddField(
            model_name='krogothgantrymasterviewcontroller',
            name='djangular_slave_vc',
            field=models.ManyToManyField(blank=True, null=True, related_name='owner', to='krogoth_gantry.KrogothGantrySlaveViewController'),
        ),
        migrations.AddField(
            model_name='krogothgantrymasterviewcontroller',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krogoth_gantry.KrogothGantryIcon'),
        ),
        migrations.AddField(
            model_name='krogothgantrymasterviewcontroller',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_krogoth_gantry.krogothgantrymasterviewcontroller_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='krogothgantrycategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krogoth_gantry.KrogothGantryIcon'),
        ),
        migrations.AddField(
            model_name='krogothgantrycategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krogoth_gantry.KrogothGantryCategory'),
        ),
        migrations.AddField(
            model_name='krogothgantrycategory',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_krogoth_gantry.krogothgantrycategory_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='AKGantryMasterViewController',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('krogoth_gantry.krogothgantrymasterviewcontroller',),
        ),
    ]
